### ISSUE TITLE
Typos in Week 4 blogpost

### ISSUE THREAD

**Issue by mxmsunny** [hunter-college-ossd-spr19/codesue-weekly#1]
Hi! There are some spelling mistakes in [your week 4 blogpost](https://github.com/hunter-college-ossd-spr19/codesue-weekly/commit/ca972d1341e85daa095dab7ae668dfa271512883?diff=split):

In line 13, "would we also track contributions such as giving a **lightening** talk at a Meetup?" should be, "...would we also track contributions such as giving a **lightning** talk at a Meetup?"

In line 17, "focusing on how to tell if a **projcet** is active" should be, "focusing on how to tell if a **project** is active"

**Comment by codesue** [comment]
Thanks for pointing these out!
